x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    platform: linux/amd64
    ports:
      - "2358:2358"
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:2358/languages"]
      interval: 20s
      timeout: 5s
      retries: 10
    restart: always
    <<: *default-logging

  worker:
    image: judge0/judge0:latest
    platform: linux/amd64
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    depends_on:
      - server
      - db
      - redis
    restart: always
    <<: *default-logging

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
    <<: *default-logging

  redis:
    image: redis:7.2.4
    command: ["/bin/sh", "-c", 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"']
    env_file: judge0.conf
    restart: always
    <<: *default-logging

volumes:
  data:
